### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by whaaaley** [baggo/baggo.github.io#1]
i don't think anyone is ever going to finish this. maybe we should just delete it.

**Comment by jamen** [comment]
@semibran is the only contributor, so I would check with him if he wants his commits destroyed.  I would leave it.  Maybe someone will feel the need to upgrade sometime.  Doesn't matter personally.

**Comment by semibran** [comment]
you can go ahead and delete it unless you have ideas for content to add. We could have some sort of section detailing what baggo is about but I don't think that kind of thing needs a separate page
